version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: lucy
      POSTGRES_PASSWORD: lucy_pass-word
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    volumes:
      - ./ecommerce_db_dump.sql:/docker-entrypoint-initdb.d/ecommerce_db_dump.sql
  
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "7241:7241"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"

volumes:
  pgdata:
    driver: local
