apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  ecommerce_db_dump.sql: |
    -- PostgreSQL database dump

    -- Dumped from database version 16.4
    -- Dumped by pg_dump version 16.4

    SET statement_timeout = 0;
    SET lock_timeout = 0;
    SET idle_in_transaction_session_timeout = 0;
    SET client_encoding = 'UTF8';
    SET standard_conforming_strings = on;
    SELECT pg_catalog.set_config('search_path', '', false);
    SET check_function_bodies = false;
    SET xmloption = content;
    SET client_min_messages = warning;
    SET row_security = off;

    SET default_tablespace = '';
    SET default_table_access_method = heap;

    -- Create the products table
    CREATE TABLE public.products (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100),
        price NUMERIC(10, 2),
        image VARCHAR(255)
    );

    -- Data for the products table
    COPY public.products (id, name, price, image) FROM stdin;
    1       Ceramic Mug     12.99   /images/mug.jpg
    2       Stainless Steel Spoon   3.49    /images/spoon.jpg
    3       Non-Stick Cooking Pot   29.99   /images/pot.jpg
    4       Microwave Oven  89.99   /images/microwave.jpg
    \.

    -- Grant permissions
    GRANT ALL ON TABLE public.products TO lucy;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "lucy"
        - name: POSTGRES_PASSWORD
          value: "lucy_pass-word"
        - name: POSTGRES_DB
          value: "ecommerce"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-sql
        configMap:
          name: postgres-init-sql

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
